### ISSUE TITLE
Expected MAST::Frame, but didn't get one

### ISSUE THREAD

**Issue by coke** [perl6/perl6-pod-to-bigpage#1]
```
$ perl6 --version
This is Rakudo version 2016.07.1 built on MoarVM version 2016.07
implementing Perl 6.c.
$ GIT_PROTOCOL=https panda install Pod::To::BigPage
==> Fetching Pod::To::BigPage
==> Building Pod::To::BigPage
==> Testing Pod::To::BigPage
===SORRY!===
Expected MAST::Frame, but didn't get one
t/P.t ..
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run

Test Summary Report
-------------------
t/P.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  3 wallclock secs ( 0.02 usr  0.01 sys +  2.57 cusr  0.13 csys =  2.73 CPU)
Result: FAIL
The spawned process exited unsuccessfully (exit code: 1)
...
```

**Comment by gfldex** [comment]
Problem comes from LWP::Simple and goes away without IO::Socket::SSL. May very well be a nativecall problem.

**Comment by tbrowder** [comment]
I had the problem, but it has gone away for me today when I did the following:

  zef uninstall LWP::Simple IO::Socket::SSL Pod::To::Bigpage
  zef install Pod::To::BigPage
  zef install IO::Socket::SSL

  cd doc # github/perl6/doc
  git checkout master
  git pull upstream master
  make xtest
  ...
  All tests successful

**Comment by jonathanstowe** [comment]
I'm still seeing this with ```Rakudo version 2016.09-7-g363a3a8 built on MoarVM version 2016.09```  having IO::Socket::SSL is non-negotiable and the dance about uninstalling it and uninstalling it should not be necessary.

Really the bug is in Rakudo as I see it as nothing should be giving rise to this kind of compiler error.

**Comment by jonathanstowe** [comment]
Also the relation with IO::Socket::SSL seems to be spurious in the sense that Pod::To::BigPage doesn't actually use any other modules, nor does the test (though the error is provoked simply with a ```require Pod::To::BigPage```) so if this actually provoked by the presence or otherwise of a certain module there is something profoundly wrong with Rakudo itself, I'm going to RT it.

**Comment by jonathanstowe** [comment]
Ah no, ignore me, it does appear that the module *does*  ```use LWP::Simple``` at line 341,  this may not always be needed so I am going to see if it can be flipped to run time.

**Comment by jonathanstowe** [comment]
See https://github.com/perl6/perl6-lwp-simple/issues/3

**Comment by jonathanstowe** [comment]
This should be fixed by the https://github.com/perl6/perl6-lwp-simple/commit/1bd887d41c1f48e287459f9b7fcaa79506a81c9a in LWP::Simple

**Comment by zoffixznet** [comment]
> This should be fixed

It is. Thanks a lot!
