### ISSUE TITLE
move this project into doc repo

### ISSUE THREAD

**Issue by tbrowder** [perl6/perl6-pod-to-bigpage#28]
The doc repo may not be the only user of this project, but it is a heavy user.  

There are currently hardwired things in this project that complicate doc repo tooling.  Moving would ease doc maintenance considerably.

## UPDATE

One solution is to dup the current lib/, bin/, and t/ into the doc repo as Doc::To::BigPage (and other renames as necessary).

**Comment by JJ** [comment]
We can just install it when building... I would rather fix what's wrong than moving it inside the already bloated (with libraries) perl6/doc repo.
Don't you think it would be better to try and fix whatever problems is causing this, than creating another problem by adding it to other repo?

**Comment by JJ** [comment]
I think I'm closing this. It's probably better to move things _out_ of the doc repo.
