### ISSUE TITLE
mystery cache

### ISSUE THREAD

**Issue by coke** [perl6/perl6-pod-to-bigpage#8]
I am trying to test timings of a full build in perl6/doc, so I want to start with a clean slate.

When I do a 'git clean -xdf', and then run 'make html', pod2onepage is emitting:

```
processed ./doc/HomePage.pod6 (cached)
processed ./doc/Language/5to6-nutshell.pod6 (cached)
processed ./doc/Language/5to6-perlfunc.pod6 (cached)
```

... where is this cached? I don't see any likely candidates in the perl6/doc checkout directory.

**Comment by JJ** [comment]
Maybe stashed in some `.precomp` dir?

**Comment by JJ** [comment]
Probably so. That file is generated via `pod2onepage` which sets up its own precomp caches:

     Str :$precomp-path = (%*ENV<TEMP> // %*ENV<TMP> // '/tmp') ~ '/PodToBigfile-precomp'
