### ISSUE TITLE
Co. perl6/doc#1845 Should we stop using .xhtml?

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/perl6-pod-to-bigpage#9]
https://github.com/perl6/perl6-pod-to-bigpage/blob/b3702e9a8d659ea899890a38e56c9dddc361848b/lib/Pod/To/BigPage.pm6#L184-L192

https://github.com/perl6/doc/issues/1845

**Comment by JJ** [comment]
Maybe make it another option...
